country_capitalized_mapping = {
        'malaysia': 'Malaysia',
        'lebanon': 'Lebanon',
        'colombia': 'Colombia',
        'romania': 'Romania',
        'south_africa': 'South Africa',
        'myanmar': 'Myanmar',
        'saudi_arabia': 'Saudi Arabia',
        'samoa': 'Samoa',
        'sudan': 'Sudan',
        'united_kingdom': 'United Kingdom',
        'australia': 'Australia',
        'taiwan': 'Taiwan',
        'thailand': 'Thailand',
        'pakistan': 'Pakistan',
        'philippines': 'Philippines',
        'sri_lanka': 'Sri Lanka',
        'north_macedonia': 'North Macedonia',
        'germany': 'Germany',
        'cambodia': 'Cambodia',
        'türkiye': 'Türkiye',
        'zimbabwe': 'Zimbabwe',
        'fiji': 'Fiji',
        'hungary': 'Hungary',
        'mexico': 'Mexico',
        'brazil': 'Brazil',
        'palestinian_territories': 'Palestinian Territories',
        'iraq': 'Iraq',
        'poland': 'Poland',
        'sweden': 'Sweden',
        'ukraine': 'Ukraine',
        'bangladesh': 'Bangladesh',
        'new_zealand': 'New Zealand',
        'france': 'France',
        'ethiopia': 'Ethiopia',
        'somalia': 'Somalia',
        'portugal': 'Portugal',
        'croatia': 'Croatia',
        'united_states_of_america': 'United States of America',
        'egypt': 'Egypt',
        'china': 'China',
        'mauritius': 'Mauritius',
        'cyprus': 'Cyprus',
        'greece': 'Greece',
        'italy': 'Italy',
        'south_sudan': 'South Sudan',
        'venezuela': 'Venezuela',
        'iran': 'Iran',
        'hong_kong': 'Hong Kong',
        'timor-leste': 'Timor-Leste',
        'austria': 'Austria',
        'india': 'India',
        'israel': 'Israel',
        'nepal': 'Nepal',
        'bosnia_and_herzegovina': 'Bosnia and Herzegovina',
        'malta': 'Malta',
        'ireland': 'Ireland',
        'peru': 'Peru',
        'vietnam': 'Vietnam',
        'singapore': 'Singapore',
        'papua_new_guinea': 'Papua New Guinea',
        'japan': 'Japan',
        'indonesia': 'Indonesia',
        'netherlands': 'Netherlands',
        'kenya': 'Kenya',
        'argentina': 'Argentina',
        'chile': 'Chile',
        'serbia': 'Serbia',
        'afghanistan': 'Afghanistan',
        'canada': 'Canada',
        'spain': 'Spain',
        'syria': 'Syria',
        'laos': 'Laos',
        'tonga': 'Tonga',
        'russia': 'Russia',
        'south_korea': 'South Korea'
    }
